name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux_release:
    name: Build on Linux
    runs-on: ubuntu-latest
    needs: create_release

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      # Step 2: Install dependencies (OS-specific)
      - name: Install dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install -y build-essential cmake libglut-dev
        shell: bash

      # Step 3: Configure (CMake)
      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        shell: bash

      # Step 4: Build
      - name: Build
        run: cmake --build build --config Release --

      - name: Generate Installer
        run: cd ./build/; cpack

      - name: upload Linux artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/*.deb

  windows_release:
    name: Build on Windows
    runs-on: windows-latest
    needs: create_release

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      # Step 2: Install dependencies (OS-specific)
      - name: Install dependencies
        run: |
          vcpkg install freeglut glew;
          choco install nsis -y
        shell: bash

      # Step 3: Configure (CMake)
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        shell: bash

      # Step 4: Build
      - name: Build
        run: cmake --build build --config Release --

      - name: Generate Installer
        run: cd ./build/; cpack

      - name: Upload Windows artifact
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./build/*.exe

  macos_release:
    name: Build on macOS
    runs-on: macos-latest
    needs: create_release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install dependencies
        run: |
          brew update
          brew install cmake freeglut glew
        shell: bash

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: cmake --build build --config Release --

      - name: Generate Installer
        run: cd build && cpack

      - name: Upload macOS artifact
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./build/*.dmg
